[inputs, props_fuel, props_ox] = engine_inputs();

% --- CH4 pump: sweep over head range ---
delta_p_CH4_range = linspace(0.5e6, 20e6, 12);  % [Pa] sweep from 0.5 to 20 MPa
pump_CH4 = pump_efficiency_iteration( ...
    inputs.m_dot_fuel, ...
    delta_p_CH4_range, ...
    props_fuel.rho, 'Methane', ...
    props_fuel.p, props_fuel.T, ...
    'Plot', true, 'PlotX', 'delta_p');

% --- LOx pump: sweep over head range ---
delta_p_LOx_range = linspace(0.5e6, 15e6, 12);  % [Pa] sweep from 0.5 to 15 MPa
pump_LOx = pump_efficiency_iteration( ...
    inputs.m_dot_oxidizer, ...
    delta_p_LOx_range, ...
    props_ox.rho, 'Oxygen', ...
    props_ox.p, props_ox.T, ...
    'Plot', true, 'PlotX', 'delta_p');

% --- Extract design-point efficiencies ---
% Find closest design points to the specified delta_p values
[~, idx_CH4] = min(abs([pump_CH4.delta_p] - inputs.delta_p_pump_LCH4));
[~, idx_LOx] = min(abs([pump_LOx.delta_p] - inputs.delta_p_pump_LOx));

inputs.eta_pump_LCH4 = pump_CH4(idx_CH4).eta;
inputs.eta_pump_LOx  = pump_LOx(idx_LOx).eta;